### ISSUE TITLE
Where Active Directory connection string is set?

### ISSUE THREAD

**Issue by afsharm** [OneBitSoftware/Microsoft.AspNetCore.Authentication.ActiveDirectory#1]
Where Active Directory connection string is set? Somewhere in appsettings?

**Comment by SharePointRadi** [comment]
Hi afsharm,

you don't set it anywhere, it is doing WIA so it is taking the current domain that the machine is part of.

R.

**Comment by seriouz** [comment]
How do i mange the case, that the authing aspnet core server, is outside of the domain?

**Comment by SharePointRadi** [comment]
The code goes through secur3s.dll and uses Windows LSA to coordinate the authentication with the domain. More details here: https://technet.microsoft.com/en-us/library/dn169014(v=ws.10).aspx

Since it is using NTLM, you can type "domain\login" when you get a login prompt.
