### ISSUE TITLE
Any plan to release a new version?

### ISSUE THREAD

**Issue by jvitor83** [OneBitSoftware/Microsoft.AspNetCore.Authentication.ActiveDirectory#2]
Want to try on the new "Microsoft.AspNetCore" packages, but it doesn't work with this package.

"Microsoft.AspNetCore.Mvc": "1.0.0"

`services.AddMvc();` gives:

```
The type 'MvcServiceCollectionExtensions' exists in both 'Microsoft.AspNet.Mvc, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

**Comment by SharePointRadi** [comment]
Yes, I need an RTM port myself, so I will be working on this tomorrow. Stay tuned.

**Comment by seriouz** [comment]
@SharePointRadi  look here https://github.com/OneBitSoftware/Microsoft.AspNetCore.Authentication.ActiveDirectory/commit/03bc45a7a1429717daa399722f6153776809f188

**Comment by jerrelblankenship** [comment]
Is there any update on this?

**Comment by SharePointRadi** [comment]
See this branch - https://github.com/OneBitSoftware/Microsoft.AspNetCore.Authentication.ActiveDirectory/tree/ASPNET_CORE_RTM_Migration 

Currently still working on it.

**Comment by SharePointRadi** [comment]
All merged in master now. Ready for consumption :)
